### ISSUE TITLE
Weekly Scrum - [March 12th, 2021]

### ISSUE THREAD

**Issue by danish1371** [SYSC4806-Project/4806-Project#23]
This week I worked on the login feature.
Next week I will finish the login feature.
Right now one issue I am having is that even though it is a valid user it is saying invalid user and not going to the dashboard.

**Comment by sandeeplayam** [comment]
This week I worked on authentication and TravisCI 
Next week I will work on finishing the incomplete features from milestone 1(TravisCI setup) and I will be creating a production and development environments for our projects
Struggling to implement Integration Tests for TravisCI, its a little confusing

**Comment by Simon-Yacoub** [comment]
This week I worked on displaying the shops and next week I hope to finish the feature.

**Comment by brougy** [comment]
This week I worked on the logic of a merchant creating a shop in the database and displaying it in plain text.
Next week I will be working on completing some features from the previous scrum. 
Attempting multiple features at once wasn't good, will slice better next time.
