### ISSUE TITLE
Weekly Scrum - [March 19th, 2021]

### ISSUE THREAD

**Issue by brougy** [SYSC4806-Project/4806-Project#24]
This week, I worked on minor adjustments in creating a shop, and database connection.
Next week, I will be working on unit and integration tests for repositories, models, and controllers. Plus some tweaking to creating shops.

**Comment by sandeeplayam** [comment]
This week I worked on finishing back-logged deliverables from milestone 1(TravisCI) and setup dev and prod environments.
Next week I will be working on Shop CRUD operations and CRUD operations for categories of shops
Integration tests are still tedious

**Comment by danish1371** [comment]
This week I worked on finishing the issues with the login feature. A user is now able to log in.
Next week I will work on integration/unit testing the model/controllers/endpoints.
There are no issues right now.
