### ISSUE TITLE
Weekly Scrum - [February 24th, 2021]

### ISSUE THREAD

**Issue by sandeeplayam** [SYSC4806-Project/4806-Project#4]
This is the same for all team members:

1) Next few days will consist of selecting a topic of interest for the group

2) Next week we will have another meeting and come up with a preliminary system design/architecture

3) School has been very busy, so it has been quite tough to get the project started

**Comment by Simon-Yacoub** [comment]
Yes

**Comment by brougy** [comment]
Agreed

**Comment by danish1371** [comment]
Yup
