### ISSUE TITLE
Weekly Scrum -  [March 1st, 2021]

### ISSUE THREAD

**Issue by sandeeplayam** [SYSC4806-Project/4806-Project#5]
This is the same for all members this week, from next scrum meeting onwards it will start to be different for all team members.

1) We have decided to go with the Mini-Shopify project topic for this semesters Sysc 4806 project.

2) Now that we have decided on the topic, we will all go and try to come up with a system design. Then in a few days we will all meetup again to discuss the individual designs we have come up with and finalize one system design for the project.

3) Usually starting a project is difficult to get up and running in the beginning, now that the ball is rolling we think it will be much better going forward.

**Comment by brougy** [comment]
Affirmative

**Comment by danish1371** [comment]
Yup
