### ISSUE TITLE
Database Schema Initial Draft

### ISSUE THREAD

**Issue by sandeeplayam** [SYSC4806-Project/4806-Project#7]
Need to create a database schema, which we can continue to build on as the project progresses. This schema will be the one referenced during implementation.

**Comment by Simon-Yacoub** [comment]
This DB Schema will be a starting point that we will use as a reference when programming. It is not final and is subject to change in the future with the implementation of new features.

**Comment by Simon-Yacoub** [comment]
![](https://media.discordapp.net/attachments/818700912729522216/819653538900738068/wAFpcnnXMOE7wAAAABJRU5ErkJggg.png)

An entity Relation Diagram that captures the general DB Schema
